version: '3.11.4'

services:
  traefik:
    image: traefik:v2.10.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Se requiere para podernos comunicar con Docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/proxy/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=paga-bot"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # Hace que traefik use el dominio con HTTP
      - "traefik.http.routers.traefik-dashboard-http.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard-http.rule=Host(`${TRAEFIK_DOMAIN}`)"
      # Hace que traefik use el dominio con HTTPS
      - "traefik.http.routers.traefik-dashboard-https.entrypoints=https"
      - "traefik.http.routers.traefik-dashboard-https.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard-https.tls=true"
      # Usa la configuracion "letsencrypt" para la generacion de los certificados
      - "traefik.http.routers.traefik-dashboard-https.tls.certresolver=letsencrypt"
      # utilice el servicio especial "traefik" api@internal con la interfaz de usuario web/dashboard
      - "traefik.http.routers.traefik-dashboard-https.service=api@internal"
      # Crea el middleware https-redirect para redireccionar HTTP to HTTPS
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      # Usa el middleware para redireccionar HTTP a HTTPS
      - "traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect"
      # Middleware admin-auth para utenticarse con el dashboard
      # Usando las variables de entorno USERNAME y HASHED_PASSWORD
      - "traefik.http.middlewares.admin-auth.basicauth.users=${TRAEFIK_USER?Varialbe not set}:${TRAEFIK_HASHED_PASSWORD?Varialbe not set}"
      - "traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth"
    networks:
      - zonas

volumes:
  traefik-public-certificates:

networks:
  zonas:
    external: true