services:
  bot:
    container_name: bot
    build:
      context: ./services/bot
      dockerfile: Dockerfile.dev
    # depends_on:
    #   - zonas-api-crud-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${BOT_PORT}", "--reload"]
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bot.loadbalancer.server.port=${BOT_PORT}"
      - "traefik.http.routers.bot-http.entrypoints=http"
      - "traefik.http.routers.bot-http.rule=Host(`${BOT_DOMAIN_DEV}`)"
    volumes:
      - ./services/bot:/bot
    environment:
      - TZ=America/Bogota
      - DEVELOPMENT_MODE=true
      - BOT_DOMAIN=${BOT_DOMAIN_DEV}
      - BOT_PORT=${BOT_PORT}
      - BOT_TOKEN=${BOT_TOKEN}
      - NGROK_TOKEN=${NGROK_TOKEN}
      - API_CRUD_URL=http://api-crud-dev:${CRUD_PORT}
    networks:
      - hic-cibus

networks:
  hic-cibus:
    external: true